# Generated by Django 5.2.7 on 2025-11-11 15:43
# Nota: Esta migration foi convertida em no-op porque o app 'departments' foi removido
# A migration 0006_remove_user_department remove este campo de qualquer forma

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # Operação removida porque o app 'departments' não existe mais
        # A migration 0006_remove_user_department já remove este campo
    ]
