# Generated by Django 5.2.7 on 2026-01-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('commercial', 'Comercial'), ('land', 'Terreno'), ('farm', 'Fazenda')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('urban', 'Urbano'), ('rural', 'Rural')], default='urban', max_length=10, verbose_name='Categoria')),
                ('transaction_type', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Aluguel'), ('both', 'Venda/Aluguel')], max_length=10, verbose_name='Transação')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Venda')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Aluguel')),
                ('original_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço anterior para exibir em promoções', max_digits=12, null=True, verbose_name='Preço Anterior de Venda')),
                ('original_rent_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço anterior para exibir em promoções', max_digits=12, null=True, verbose_name='Preço Anterior de Aluguel')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Quartos')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Banheiros')),
                ('garage_spaces', models.PositiveIntegerField(default=0, verbose_name='Vagas')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='Imagem Principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
