# Generated by Django 5.2.7 on 2026-01-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0005_delete_landingpagetheme_and_more'),
        ('properties', '0002_rename_landing_page_to_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('urban', 'Urbano'), ('rural', 'Rural')], default='urban', max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='property',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landings.site', verbose_name='Site'),
        ),
    ]
