# Generated by Django 5.2.7 on 2026-01-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_category_alter_property_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='original_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço anterior para exibir em promoções', max_digits=12, null=True, verbose_name='Preço Anterior de Aluguel'),
        ),
        migrations.AddField(
            model_name='property',
            name='original_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço anterior para exibir em promoções', max_digits=12, null=True, verbose_name='Preço Anterior de Venda'),
        ),
    ]
