# Generated by Django 5.2.7 on 2026-01-07 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_message_dismissed', models.BooleanField(default=False, help_text='Indica se o usuário fechou a mensagem de conclusão do onboarding', verbose_name='Mensagem de conclusão dispensada')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Data e hora em que a mensagem de conclusão foi dispensada', null=True, verbose_name='Data de dispensa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Status de Onboarding',
                'verbose_name_plural': 'Status de Onboarding',
                'ordering': ['-updated_at'],
            },
        ),
    ]
