# Generated by Django 5.2.7 on 2026-01-08 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(help_text='Ex: fulano → fulano.propzy.com.br', unique=True, verbose_name='Subdomínio')),
                ('custom_domain', models.CharField(blank=True, help_text='Ex: www.imobiliariafulano.com.br', max_length=255, null=True, unique=True, verbose_name='Domínio Personalizado')),
                ('ssl_status', models.CharField(choices=[('none', 'Sem SSL'), ('generating', 'Gerando...'), ('active', 'Ativo'), ('error', 'Erro')], default='none', help_text='Status do certificado SSL do domínio personalizado', max_length=20, verbose_name='Status SSL')),
                ('ssl_error', models.TextField(blank=True, help_text='Mensagem de erro se falhar geração do SSL', null=True, verbose_name='Erro SSL')),
                ('dns_status', models.CharField(choices=[('pending', 'Pendente'), ('ok', 'Configurado'), ('error', 'Erro')], default='pending', help_text='Status da configuração DNS do domínio personalizado', max_length=20, verbose_name='Status DNS')),
                ('dns_error', models.TextField(blank=True, help_text='Mensagem de erro se DNS não estiver configurado', null=True, verbose_name='Erro DNS')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nome do Negócio')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
                ('hero_image', models.ImageField(blank=True, upload_to='heroes/', verbose_name='Imagem Principal/Banner')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Formato: 5569999999999 (DDI+DDD+número)', max_length=20, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('meta_title', models.CharField(blank=True, help_text='Para SEO (Google)', max_length=60, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, help_text='Para SEO (Google)', max_length=160, verbose_name='Meta Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_published', models.BooleanField(default=False, help_text='Visível publicamente', verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('theme', models.ForeignKey(help_text='Selecione o tema/layout do site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.theme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'landings_landingpage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#006DFF', help_text='Cor principal do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Cor secundária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Secundária')),
                ('tertiary_color', models.CharField(default='#9333ea', help_text='Cor terciária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Terciária')),
                ('quaternary_color', models.CharField(default='#f59e0b', help_text='Cor quaternária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Quaternária')),
                ('success_color', models.CharField(default='#10b981', help_text='Cor para mensagens de sucesso (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Sucesso')),
                ('danger_color', models.CharField(default='#ef4444', help_text='Cor para mensagens de erro (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Erro')),
                ('warning_color', models.CharField(default='#f59e0b', help_text='Cor para mensagens de aviso (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Aviso')),
                ('info_color', models.CharField(default='#3b82f6', help_text='Cor para mensagens informativas (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Informação')),
                ('text_primary_color', models.CharField(default='#13112F', help_text='Cor principal do texto (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Texto Primária')),
                ('text_secondary_color', models.CharField(default='#585F76', help_text='Cor secundária do texto (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Texto Secundária')),
                ('background_color', models.CharField(default='#EBECF4', help_text='Cor de fundo principal (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Fundo')),
                ('border_color', models.CharField(default='#d8dae8', help_text='Cor das bordas (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Borda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='landings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Design do Site',
                'verbose_name_plural': 'Designs dos Sites',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_config', models.JSONField(blank=True, default=dict, help_text='Configurações de cada seção do tema', verbose_name='Configurações das Seções')),
                ('sections_order', models.JSONField(blank=True, default=list, help_text='Lista com a ordem de exibição das seções', verbose_name='Ordem das Seções')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='landings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Configuração do Tema',
                'verbose_name_plural': 'Configurações dos Temas',
            },
        ),
    ]
