# Generated by Django 5.2.7 on 2026-01-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Nome da pasta do tema. Ex: modern, classic', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão')),
                ('category', models.CharField(choices=[('modern', 'Moderno'), ('classic', 'Clássico'), ('minimal', 'Minimalista'), ('luxury', 'Luxuoso'), ('corporate', 'Corporativo')], default='modern', max_length=20, verbose_name='Categoria')),
                ('screenshot', models.ImageField(blank=True, help_text='Preview do tema', upload_to='themes/screenshots/', verbose_name='Screenshot')),
                ('default_primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor Primária Padrão')),
                ('default_secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundária Padrão')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não aparece para seleção', verbose_name='Ativo')),
                ('is_premium', models.BooleanField(default=False, help_text='Requer plano premium', verbose_name='Premium')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de recursos do tema', verbose_name='Recursos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tema de Landing Page',
                'verbose_name_plural': 'Temas de Landing Pages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(help_text='Ex: fulano → fulano.propzy.com.br', unique=True, verbose_name='Subdomínio')),
                ('custom_domain', models.CharField(blank=True, help_text='Ex: www.imobiliariafulano.com.br', max_length=255, null=True, unique=True, verbose_name='Domínio Personalizado')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nome do Negócio')),
                ('business_description', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
                ('hero_image', models.ImageField(blank=True, upload_to='heroes/', verbose_name='Imagem Principal/Banner')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Formato: 5569999999999 (DDI+DDD+número)', max_length=20, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('primary_color', models.CharField(default='#007bff', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor Secundária')),
                ('meta_title', models.CharField(blank=True, help_text='Para SEO (Google)', max_length=60, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, help_text='Para SEO (Google)', max_length=160, verbose_name='Meta Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_published', models.BooleanField(default=False, help_text='Visível publicamente', verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('theme', models.ForeignKey(help_text='Selecione o tema/layout da landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landings.landingpagetheme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('commercial', 'Comercial'), ('land', 'Terreno'), ('farm', 'Fazenda')], max_length=20, verbose_name='Tipo')),
                ('transaction_type', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Aluguel'), ('both', 'Venda/Aluguel')], max_length=10, verbose_name='Transação')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Venda')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Aluguel')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Quartos')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Banheiros')),
                ('garage_spaces', models.PositiveIntegerField(default=0, verbose_name='Vagas')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='Imagem Principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landings.landingpage', verbose_name='Landing Page')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landings.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
