# Generated by Django 5.2.7 on 2026-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='dns_error',
            field=models.TextField(blank=True, help_text='Mensagem de erro se DNS não estiver configurado', null=True, verbose_name='Erro DNS'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='dns_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('ok', 'Configurado'), ('error', 'Erro')], default='pending', help_text='Status da configuração DNS do domínio personalizado', max_length=20, verbose_name='Status DNS'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ssl_error',
            field=models.TextField(blank=True, help_text='Mensagem de erro se falhar geração do SSL', null=True, verbose_name='Erro SSL'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ssl_status',
            field=models.CharField(choices=[('none', 'Sem SSL'), ('generating', 'Gerando...'), ('active', 'Ativo'), ('error', 'Erro')], default='none', help_text='Status do certificado SSL do domínio personalizado', max_length=20, verbose_name='Status SSL'),
        ),
    ]
