# Generated by Django 5.2.7 on 2026-01-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0002_landingpage_dns_error_landingpage_dns_status_and_more'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.ForeignKey(help_text='Selecione o tema/layout da landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.theme', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='property',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_deprecated', to='landings.landingpage', verbose_name='Landing Page'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_deprecated', to='landings.property', verbose_name='Imóvel'),
        ),
    ]
