# Generated by Django 5.2.7 on 2026-01-05 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_rename_landingpage_to_site'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageTheme',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='site',
            name='theme',
            field=models.ForeignKey(help_text='Selecione o tema/layout do site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.theme', verbose_name='Tema'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
