# Generated by Django 5.2.7 on 2026-01-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0005_delete_landingpagetheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_config', models.JSONField(blank=True, default=dict, help_text='Configurações de cada seção do tema', verbose_name='Configurações das Seções')),
                ('sections_order', models.JSONField(blank=True, default=list, help_text='Lista com a ordem de exibição das seções', verbose_name='Ordem das Seções')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='landings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Configuração do Tema',
                'verbose_name_plural': 'Configurações dos Temas',
            },
        ),
    ]
