# Generated by Django 5.2.7 on 2026-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_themesectionconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='business_description',
        ),
    ]
