# Generated by Django 5.2.7 on 2026-01-07 17:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_colors(apps, schema_editor):
    """Migra as cores existentes do Site para o novo modelo SiteDesign"""
    Site = apps.get_model('landings', 'Site')
    SiteDesign = apps.get_model('landings', 'SiteDesign')

    for site in Site.objects.all():
        # Criar SiteDesign para cada site existente
        design, created = SiteDesign.objects.get_or_create(site=site)

        # Se o site tinha cores personalizadas, migrar para o design
        if hasattr(site, 'primary_color') and site.primary_color:
            design.primary_color = site.primary_color
        if hasattr(site, 'secondary_color') and site.secondary_color:
            design.secondary_color = site.secondary_color

        design.save()


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0007_remove_business_description'),
    ]

    operations = [
        # Primeiro criar o modelo SiteDesign
        migrations.CreateModel(
            name='SiteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#006DFF', help_text='Cor principal do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Cor secundária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Secundária')),
                ('tertiary_color', models.CharField(default='#9333ea', help_text='Cor terciária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Terciária')),
                ('quaternary_color', models.CharField(default='#f59e0b', help_text='Cor quaternária do tema (formato: #RRGGBB)', max_length=7, verbose_name='Cor Quaternária')),
                ('success_color', models.CharField(default='#10b981', help_text='Cor para mensagens de sucesso (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Sucesso')),
                ('danger_color', models.CharField(default='#ef4444', help_text='Cor para mensagens de erro (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Erro')),
                ('warning_color', models.CharField(default='#f59e0b', help_text='Cor para mensagens de aviso (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Aviso')),
                ('info_color', models.CharField(default='#3b82f6', help_text='Cor para mensagens informativas (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Informação')),
                ('text_primary_color', models.CharField(default='#13112F', help_text='Cor principal do texto (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Texto Primária')),
                ('text_secondary_color', models.CharField(default='#585F76', help_text='Cor secundária do texto (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Texto Secundária')),
                ('background_color', models.CharField(default='#EBECF4', help_text='Cor de fundo principal (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Fundo')),
                ('border_color', models.CharField(default='#d8dae8', help_text='Cor das bordas (formato: #RRGGBB)', max_length=7, verbose_name='Cor de Borda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='landings.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Design do Site',
                'verbose_name_plural': 'Designs dos Sites',
                'ordering': ['-updated_at'],
            },
        ),
        # Migrar dados existentes
        migrations.RunPython(
            migrate_existing_colors,
            reverse_code=migrations.RunPython.noop,
        ),
        # Agora remover os campos antigos
        migrations.RemoveField(
            model_name='site',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='site',
            name='secondary_color',
        ),
    ]
