# Generated by Django 5.2.7 on 2026-01-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Nome da pasta do tema. Ex: modern, classic', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão')),
                ('category', models.CharField(choices=[('modern', 'Moderno'), ('classic', 'Clássico'), ('minimal', 'Minimalista'), ('luxury', 'Luxuoso'), ('corporate', 'Corporativo')], default='modern', max_length=20, verbose_name='Categoria')),
                ('screenshot', models.ImageField(blank=True, help_text='Preview do tema', upload_to='themes/screenshots/', verbose_name='Screenshot')),
                ('default_primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor Primária Padrão')),
                ('default_secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundária Padrão')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não aparece para seleção', verbose_name='Ativo')),
                ('is_premium', models.BooleanField(default=False, help_text='Requer plano premium', verbose_name='Premium')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de recursos do tema', verbose_name='Recursos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
