# Generated by Django 5.0.1 on 2025-12-31 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domínio')),
                ('type', models.CharField(choices=[('subdomain', 'Subdomínio'), ('custom', 'Domínio Personalizado')], default='subdomain', max_length=20, verbose_name='Tipo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de Verificação')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='domains_dom_domain_b16702_idx'), models.Index(fields=['is_verified'], name='domains_dom_is_veri_f648b6_idx')],
            },
        ),
    ]
